jobs:
  test-and-build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    - continue-on-error: true
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: yes
name: Check Markdown links
on:
  repository_dispatch:
    types: trigger-ga___check_dead_links.yml
